WITH CTE AS (
    SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
    HAVING PARENT_ID IS NOT NULL -- 조인할 것 생각하면 HAVING절은 없어도 될 듯
)

SELECT ID, IFNULL(CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA e
LEFT JOIN CTE c ON e.ID = c.PARENT_ID 
ORDER BY ID