# 결과도 똑같이 나오고 GROUP BY도 문제 없이 되는데 이 쿼리는 오답이라고 뜬다 타입 때문인가? 문제 설명이 부족해서 아쉽다
# SELECT DATE_FORMAT(YM, '%Y') AS "YEAR", ROUND(AVG(PM_VAL1), 2) AS "PM10", ROUND(AVG(PM_VAL2), 2) AS "PM2.5"
# FROM AIR_POLLUTION
# WHERE LOCATION2 = '수원'
# GROUP BY DATE_FORMAT(YM, '%Y')
# ORDER BY YEAR

SELECT YEAR(YM) AS "YEAR", ROUND(AVG(PM_VAL1), 2) AS "PM10", ROUND(AVG(PM_VAL2), 2) AS "PM2.5"
FROM AIR_POLLUTION
WHERE LOCATION2 = '수원'
GROUP BY YEAR(YM)
ORDER BY YEAR