WITH CTE AS (
    SELECT *, MAX(FAVORITES) OVER (PARTITION BY FOOD_TYPE) AS MAX_FAVORITES
    FROM REST_INFO
)

SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX_FAVORITES AS FAVORITES
FROM CTE
WHERE FAVORITES = MAX_FAVORITES
ORDER BY FOOD_TYPE DESC