-- NTILE로도 풀어 보기!

WITH CTE AS ( 
    SELECT ID,
           PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS COLONY_RANK
    FROM ECOLI_DATA
)

SELECT ID, 
       CASE
           WHEN COLONY_RANK <= 0.25 THEN 'CRITICAL'
           WHEN COLONY_RANK <= 0.5 THEN 'HIGH'
           WHEN COLONY_RANK <= 0.75 THEN 'MEDIUM'
           ELSE 'LOW'
       END AS COLONY_NAME
FROM CTE
ORDER BY ID