# 1이면 대여중, 0이면 대여 가능
WITH ava_num AS (
    SELECT CAR_ID, IF(DATE('2022-10-16') BETWEEN START_DATE AND END_DATE, 1, 0) AS AVAILABILITY_NUM
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
)

# CAR_ID로 GROUP BY 했을 때 하나라도 1이면 대여중, 모두 0이면 대여 가능
SELECT CAR_ID, IF(SUM(AVAILABILITY_NUM) > 0, '대여중', '대여 가능') AS AVAILABILITY
FROM ava_num
GROUP BY CAR_ID
ORDER BY CAR_ID DESC