WITH TOP_ID AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)

SELECT CONCAT('/home/grep/src/', t.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM TOP_ID t
JOIN USED_GOODS_FILE f ON t.BOARD_ID = f.BOARD_ID
ORDER BY FILE_ID DESC