SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
WHERE 1 = 1
      AND SALES_DATE LIKE '2022-01%'
GROUP BY CATEGORY
ORDER BY CATEGORY

# SELECT *
# FROM BOOK b
# JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
# WHERE 1 = 1
#       AND SALES_DATE LIKE '2022-01%'
